avatar: /avatar/archer.jpeg
author: JFkh
signature: Have withstood pain to create many weapons.
social:
  github: https://github.com/Stefankeep
  wechat: /assets/wechat.png
friends:
  常用资源文件: http://res.zyarcher.com
about:
  enable: false
  image: '/intro/about-bg.jpg'

SEO_title: 无败亦无胜
SEO_keywords:
  - Notar
  - '多余寡欢'
  - Springboot
main_title: 子原文档
subtitle: Have withstood pain to create many weapons.
site_header_image: '/assets/bg/vacant-blue-armchairs-3163715.jpg'
post_header_image: '/intro/post-bg.jpg'
_404_image: '/intro/404-bg.jpg'

algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts # 搜索栏 placeholder
    hits_empty: "We did not find any results for the search: ${query}" # 搜索结果提示
    hits_stats: "${hits} results found in ${time} ms" # 搜索无结果的提示

comment:
  livere_uid:
  disqus_shortname:
  gitment_owner:
  gitment_repo:
  gitment_client_id:
  gitment_client_secret:
  youyan_uid:
  valine_appId:
  valine_appKey:
  valine_placeHolder:

busuanzi: false
busuanzi_pv_or_uv: 'pv'
busuanzi_slug: 'PV: ${count} :)'
baidu_analytics:
google_analytics:
CNZZ_analytics:

favicon:  /assets/favicon.ico
truncate_length:
toc: true
reading_info: true
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50

copyright:
  enable: true
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
