# ========== 资料栏 ========== #
# 头像路径
avatar: /avatar/archer.jpeg
# 博主名字，不填写该字段则默认采用 Hexo 配置文件中的 author 字段
author: JFkh
# 博客签名
signature: Have withstood pain to create many weapons.
# 社交账号(可以自定义顺序)
social:
  email: 1057520209@qq.com
  github: https://github.com/Stefankeep
  # wechat 和 qq 需要填写二维码图片的路径
  wechat: /assets/wechat.png
#  qq:
#  telegram:
#  weibo:
#  zhihu:
#  douban:
#  facebook:
#  twitter:
#  instagram:
#  stack-overflow:
#  segmentFault:
#  juejin:
#  v2ex:
#  linkedin:
#  blog:
#  others:
#  rss: /atom.xml
# 友链
friends:
  friendA: //www.baidu.com
  friendB: //www.baidu.com
  friendC:
# about 页面
about:
  # 是否启用 about 页
  enable: true
  # about 页头图
  image: '/intro/about-bg.jpg'

# ========== Site ========== #
# title of the site (good for SEO)
SEO_title: fi3ework's Studio
# keywords for site (good for SEO)
SEO_keywords:
  - hexo
  - 'hexo-theme'
  - 'hexo-blog'
# main title shown in header image
main_title: 多余寡欢的日常
# subtitle
subtitle: Have withstood pain to create many weapons.
# site haeder image
site_header_image: '/intro/index-bg.jpg'
# post haeder image
post_header_image: '/intro/post-bg.jpg'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== 搜索 ========== #
algolia_search:
  enable: false
  hits:
    per_page: 10 # 每页的结果数
  labels:
    input_placeholder: Search for Posts # 搜索栏 placeholder
    hits_empty: "We did not find any results for the search: ${query}" # 搜索结果提示
    hits_stats: "${hits} results found in ${time} ms" # 搜索无结果的提示

# ========== 评论插件 ========== #
# 目前支持直接添加 Livere，Disqus，Gitment，友言及 Valine，填写插件对应的字段即可启用。(推荐使用 Livere)
# 如果想添加其他评论插件，在 custom.ejs 中添加即可。
comment:
  # Livere 官网：https://livere.com/
  livere_uid:
  # Disqus 官网：https://disqus.com/
  disqus_shortname:
  # Gitment 官网：https://github.com/imsun/gitment
  gitment_owner:
  gitment_repo:
  gitment_client_id:
  gitment_client_secret:
  # 友言 官网: http://www.uyan.cc/
  youyan_uid:
  # Valine 官网: https://valine.js.org/
  valine_appId:
  valine_appKey:
  valine_placeHolder:

# ========== 统计 ========== #
# 是否开启不蒜子阅读量统计
busuanzi: true
# 统计方式，填写 pv 或 uv
busuanzi_pv_or_uv: 'pv'
# 自定义统计标语，'${count}' 会自动替换成统计值
busuanzi_slug: 'PV: ${count} :)'
# 百度统计(填写 siteID)
baidu_analytics:
# Google统计(填写 siteID)
google_analytics:
# CNZZ统计
CNZZ_analytics:

# ========== 其他 ========== #
# 网站的标签页缩略图
favicon:  /assets/favicon.ico
# 首页的文章摘要字数(默认300，填0则不显示摘要)
truncate_length:
# 开启文章右侧的大纲
toc: true
# 字数统计 & 阅读时间
reading_info: true
# 头图高度 (默认是屏幕高度的 50%, 可以直接输入其他数字)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50

copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
